### ISSUE TITLE
Export Smart Story as a printable image

### ISSUE THREAD

**Issue by PaulH74** [otakudaddy/smartstory_issue_tracker#3]
Hi Charlie,

Would it be possible to implement an export feature which allows us to generate a high resolution jpeg (or equivalent) image of the smart story "layout"?

This would be a useful visual aid which would help during testing phase.

Ideally, the background would be converted to white (to allow for printing).

![image](https://user-images.githubusercontent.com/21220682/52981626-f2534d00-3434-11e9-83c5-a56ed2e62dc7.png)

Thank you,
Paul

**Comment by otakudaddy** [comment]
it is possible - i'll get back to you on ETA

**Comment by otakudaddy** [comment]
There is a functioning download image button now

**Comment by PaulH74** [comment]
Thanks Charlie
