### ISSUE TITLE
Change / Edit Entities after creating them.

### ISSUE THREAD

**Issue by PaulH74** [otakudaddy/smartstory_issue_tracker#5]
Hi Charlie,

Is there a way to edit a story.choice entity after it has been created and added?

If not, is it possible to add this feature, please?

For example, I've created 'drink' and 'water' entities under story.choice.  I would like to be able to add / remove associated synonyms at a later stage.

![image](https://user-images.githubusercontent.com/21220682/52982429-1ebd9800-343a-11e9-8dd8-6cb6d74d20c9.png)

Thank you,
Paul

**Comment by otakudaddy** [comment]
Hi Paul,

At the moment, the only way to edit them is to go into Dialogflow and add/remove synonyms there.
At some point you'll be able to edit them in project, but it won't happen for a few weeks at least because of other priorities...

**Comment by PaulH74** [comment]
Hi Charlie,

No - that's ok - as long as there's a way, I am happy to edit in Dialogflow.

Thank you.
