### ISSUE TITLE
URGENT ISSUE: Story 04 requires "re-UPLOADing" from .json file each time home page is reloaded.

### ISSUE THREAD

**Issue by PaulH74** [otakudaddy/smartstory_issue_tracker#7]
Story 04 requires "re-UPLOADing" from local file each time home page is reloaded - it does not save online, requiring constant 'export' / 'import' during editing process.

**Comment by otakudaddy** [comment]
Hi Paul,

Hm... I've uploaded the copy you sent me and it seems to be staying/saving. Could you send me the file you're uploading?

**Comment by PaulH74** [comment]
Hi Charlie,

This was the file I initially uploaded this morning to work on.

Unfortunately, I've lost the work I've done as I hadn't "re-exported" it, but simply saved online.

I can see Story 04 is back on the home page, though, so I'll edit it shortly.

Thanks for your prompt response to this issue.

Paul

________________________________

**Comment by otakudaddy** [comment]
Let me know how it goes... I

**Comment by PaulH74** [comment]
Hi Charlie,

Still having trouble with this - have lost 04 again.  It's not appearing on the home page.


________________________________

**Comment by otakudaddy** [comment]
Give me a minute...

**Comment by PaulH74** [comment]
Issue resolved with story being trimmed down in size.
